server:
  port: 8080
  servlet:
    context-path: /desafio
spring:
  application:
    name: DesafioTecnico
    kafka:
      auto.create.topics.enable: true
      consumer:
        bootstrap-servers: kafka:29092
        group-id: resultados
        auto-offset-reset: earliest
  datasource:
    url: jdbc:mysql://localhost:3306/desafio_tecnico?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    initialization-mode: always
  jpa:
    generate-ddl: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  quartz:
    properties:
      org.quartz.jobStore:
        isClustered: true
      org.quartz.scheduler:
        instanceId: AUTO
      jobStore:
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        isClustered: true
    job-store-type: jdbc
    initialize-schema: never
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
