spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS TESTDB;
  test:
    database:
      replace: NONE
  jpa:
    default_schema: TESTDB
    generate-ddl: true
    hibernate:
      ddl-auto: update